filter:
  excluded_paths:
    - demo/*
    - dist/*
checks:
  javascript:
    no_else_return: true
    eqeqeq: true
build:
  nodes:
    analysis:
      environment:
        elasticsearch: false
        memcached: false
        mongodb: false
        neo4j: false
        node: '9.3.0'
        postgresql: false
        rabbitmq: false
        redis: false
      tests:
        override:
          - js-scrutinizer-run


